return {
    Id = "AttackCapture",
    Label = "Combate",
    Icon = "target",
    Bookmarked = false,
    RuntimeModule = "runtime/AttackCapture.lua",
    Sections = {
        {
            Title = "Captura guiada",
            Icon = "search",
            Controls = {
                {
                    Kind = "Paragraph",
                    Id = "attack_help",
                    Label = "Capture Push, soco e armas separadamente",
                    Description = "Inicie antes de equipar. Equipe uma ferramenta, use uma vez e tente novamente durante a recarga. Encerre e copie. Repita em outra coleta para a próxima arma.",
                    Height = 98,
                },
                {
                    Kind = "Input",
                    Setting = "CaptureLabel",
                    Id = "attack_capture_label",
                    Label = "Nome deste teste",
                    Placeholder = "Push — Red Light/Green Light",
                    Default = "Push — Red Light/Green Light",
                },
                {
                    Kind = "Toggle",
                    Setting = "CaptureInbound",
                    Id = "attack_capture_inbound",
                    Label = "Registrar respostas do servidor",
                    Description = "Preserva eventos recebidos próximos das ativações e eventos com nomes ligados a combate.",
                    Default = true,
                },
                {
                    Kind = "Button",
                    Setting = "StartAttackCapture",
                    Id = "start_attack_capture",
                    Label = "Iniciar antes de equipar",
                    Description = "Observa todas as Tools, ativações, estados e chamadas enviadas pelo jogo sem executar ataques.",
                    ButtonText = "Iniciar",
                },
                {
                    Kind = "Button",
                    Setting = "FinishAttackCapture",
                    Id = "finish_attack_capture",
                    Label = "Encerrar e analisar",
                    Description = "Use depois do ataque normal e da tentativa feita durante a recarga.",
                    ButtonText = "Analisar",
                },
                {
                    Kind = "Button",
                    Setting = "CopyAttackCapture",
                    Id = "copy_attack_capture",
                    Label = "Copiar relatório completo",
                    Description = "Encerra automaticamente uma coleta ativa antes de copiar.",
                    ButtonText = "Copiar",
                },
                {
                    Kind = "Button",
                    Setting = "ClearAttackCapture",
                    Id = "clear_attack_capture",
                    Label = "Limpar captura de combate",
                    ButtonText = "Limpar",
                },
            },
        },
        {
            Title = "Resultado",
            Icon = "info",
            Controls = {
                {
                    Kind = "Paragraph",
                    Id = "attack_status",
                    Label = "Aguardando captura",
                    Description = "Faça uma coleta para o Push e outra para o soco ou arma diferente.",
                    Height = 82,
                },
                {
                    Kind = "Paragraph",
                    Id = "attack_report",
                    Label = "Prévia da investigação",
                    Description = "Ativações, remotes e mudanças de estado aparecerão aqui.",
                    Height = 400,
                },
            },
        },
    },
}
