return {
    Id = "Baby",
    Label = "Bebê",
    Icon = "users",
    Bookmarked = false,
    RuntimeModule = "runtime/Baby.lua",
    Sections = {
        {
            Title = "Coleta guiada",
            Icon = "search",
            Controls = {
                {
                    Kind = "Paragraph",
                    Id = "baby_help",
                    Label = "1. Inicie carregando o bebê  •  2. Solte  •  3. Pegue normalmente  •  4. Copie",
                    Description = "A coleta observa os remotes recebidos, tenta registrar chamadas enviadas pelo jogo, salva mudanças do seu personagem e examina objetos criados perto da posição do drop.",
                    Height = 82,
                },
                {
                    Kind = "Slider",
                    Setting = "BabyScanRadius",
                    Id = "baby_scan_radius",
                    Label = "Raio ao redor do bebê",
                    Description = "Distância usada para detalhar prompts, detectores, peças e modelos ao redor do CFrame recebido em dropBaby.",
                    Min = 15,
                    Max = 150,
                    Default = 60,
                    Step = 5,
                },
                {
                    Kind = "Button",
                    Setting = "StartBabyCapture",
                    Id = "start_baby_capture",
                    Label = "Iniciar enquanto estiver carregando",
                    Description = "Salva a base e começa a observar. Depois deste clique, solte e pegue o bebê normalmente.",
                    ButtonText = "Iniciar",
                },
                {
                    Kind = "Button",
                    Setting = "FinishBabyCapture",
                    Id = "finish_baby_capture",
                    Label = "Encerrar e analisar",
                    Description = "Finalize depois de pegar o bebê novamente.",
                    ButtonText = "Analisar",
                },
                {
                    Kind = "Button",
                    Setting = "CopyBabyCapture",
                    Id = "copy_baby_capture",
                    Label = "Copiar relatório completo",
                    Description = "Se a coleta ainda estiver ativa, ela será encerrada automaticamente antes da cópia.",
                    ButtonText = "Copiar",
                },
                {
                    Kind = "Button",
                    Setting = "ClearBabyCapture",
                    Id = "clear_baby_capture",
                    Label = "Limpar coleta do bebê",
                    ButtonText = "Limpar",
                },
            },
        },
        {
            Title = "Resultado",
            Icon = "info",
            Controls = {
                {
                    Kind = "Paragraph",
                    Id = "baby_status",
                    Label = "Aguardando coleta",
                    Description = "Inicie a coleta enquanto o bebê ainda estiver com você.",
                    Height = 78,
                },
                {
                    Kind = "Paragraph",
                    Id = "baby_report",
                    Label = "Prévia da investigação",
                    Description = "Os eventos e candidatos de interação aparecerão aqui.",
                    Height = 360,
                },
            },
        },
    },
}
