return {
    Id = "MusicalChairs",
    Label = "Cadeiras",
    Icon = "search",
    Bookmarked = false,
    RuntimeModule = "runtime/MusicalChairs.lua",
    Sections = {
        {
            Title = "Coleta guiada completa",
            Icon = "search",
            Controls = {
                {
                    Kind = "Paragraph",
                    Id = "chairs_help",
                    Label = "Inicie antes da música e marque cada estado durante a rodada",
                    Description = "Registra Humanoid.Sit/SeatPart, Seat.Occupant, SeatWeld, estrutura próxima, prompts, remotes e mudanças. Não senta, não move e não dispara nada.",
                    Height = 96,
                },
                {
                    Kind = "Slider",
                    Setting = "ChairScanRadius",
                    Id = "chairs_scan_radius",
                    Label = "Raio da estrutura próxima",
                    Description = "Inclui peças genéricas ao redor do personagem mesmo quando não possuem chair ou seat no nome.",
                    Min = 10,
                    Max = 120,
                    Default = 45,
                    Step = 5,
                },
                {
                    Kind = "Slider",
                    Setting = "ChairCandidateLimit",
                    Id = "chairs_candidate_limit",
                    Label = "Limite por fotografia",
                    Description = "Quantidade máxima de Seats, juntas, interações e peças próximas detalhadas em cada marcação.",
                    Min = 50,
                    Max = 300,
                    Default = 160,
                    Step = 10,
                },
                {
                    Kind = "Toggle",
                    Setting = "CaptureAllChairRemotes",
                    Id = "chairs_all_remotes",
                    Label = "Preservar todos os remotes recebidos",
                    Description = "Desligado mantém apenas eventos relacionados à fase, cadeira, estado, timer e eliminação.",
                    Default = false,
                },
                {
                    Kind = "Button",
                    Setting = "StartChairsCapture",
                    Id = "start_chairs_capture",
                    Label = "1. Iniciar antes da música",
                    Description = "Salva a base e começa a observar a rodada inteira.",
                    ButtonText = "Iniciar",
                },
                {
                    Kind = "Button",
                    Setting = "MarkChairFree",
                    Id = "mark_chair_free",
                    Label = "2. Registrar cadeira livre",
                    Description = "Use perto de uma cadeira antes de alguém sentar nela.",
                    ButtonText = "Marcar livre",
                },
                {
                    Kind = "Button",
                    Setting = "MarkRealSeat",
                    Id = "mark_real_seat",
                    Label = "3. Registrar sentado de verdade",
                    Description = "Sente normalmente e clique enquanto ainda estiver ocupando a cadeira real.",
                    ButtonText = "Marcar real",
                },
                {
                    Kind = "Button",
                    Setting = "MarkAirSeat",
                    Id = "mark_air_seat",
                    Label = "4. Registrar sentado no ar",
                    Description = "Opcional: ative o teste do HMenu e marque para comparar com a cadeira real.",
                    ButtonText = "Marcar no ar",
                },
                {
                    Kind = "Button",
                    Setting = "FinishChairsCapture",
                    Id = "finish_chairs_capture",
                    Label = "5. Encerrar após a eliminação/limpeza",
                    Description = "Salva o estado final e monta o relatório comparativo.",
                    ButtonText = "Analisar",
                },
                {
                    Kind = "Button",
                    Setting = "CopyChairsCapture",
                    Id = "copy_chairs_capture",
                    Label = "6. Copiar relatório completo",
                    Description = "Encerra automaticamente uma captura ativa e copia tudo para enviar.",
                    ButtonText = "Copiar",
                },
                {
                    Kind = "Button",
                    Setting = "ClearChairsCapture",
                    Id = "clear_chairs_capture",
                    Label = "Limpar coleta das cadeiras",
                    ButtonText = "Limpar",
                },
            },
        },
        {
            Title = "Resultado",
            Icon = "info",
            Controls = {
                {
                    Kind = "Paragraph",
                    Id = "chairs_status",
                    Label = "Aguardando coleta",
                    Description = "Inicie antes da música e faça as marcações na ordem indicada.",
                    Height = 86,
                },
                {
                    Kind = "Paragraph",
                    Id = "chairs_report",
                    Label = "Prévia da investigação",
                    Description = "Estados, assentos, juntas e eventos relevantes aparecerão aqui.",
                    Height = 400,
                },
            },
        },
    },
}
